url: https://IzaakBeekman.com
enforce_ssl: IzaakBeekman.com
baseurl:

exclude: [Gemfile, Gemfile.lock]

# Site settings
title: Izaak Beekman
email: zbeekman@gmail.com
description: "Izaak Beekman: Aerospace Engineer, Programmer, Data Scientist"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2863a6
  secondary: 259bc8
  secondary-dark: "203634"
  nav-bar: "868686"

# Team names, titles and social links
people:
- name: Izaak Beekman
  pic: 1
  position: Ph. D. Aerospace Engineering
  social:
    - title: linkedin
      url: https://linkedin.com/in/zbeekman
    - title: github
      url: https://github.com/zbeekman
    - title: twitter
      url: https://twitter.com/zbeekman

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/zbeekman
  - title: github
    url: https://github.com/zbeekman
  - title: twitter
    url: https://twitter.com/zbeekman

# Postal address (add as many lines as necessary)
address:
  - line: Izaak Beekman
  - line: 1245 13th St. NW
  - line: Apt. 1010
  - line: Washington DC, 20005

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM


# Try merging all the css again and use native jekyll/sass minification
sass:
  sass_dir: _sass
  style: compressed


# GH-pages supported plugins
gems:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap


# jekyll-compress-html
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
